// <auto-generated/>
using Microsoft.AspNetCore.Components;
using Microsoft.EntityFrameworkCore;
using SmartHome.Shared.Entities;
using SmartHome.Shared.Persistence;

namespace SmartHome.Frontend.Components.Pages.Dispositivos;

public partial class MinisIndexComponent : ComponentBase
{
    [Inject]
    private IDbContextFactory<SmartHomeDbContext> DbContextFactory { get; set; } = default!;

    private List<MiniDTO>? DevicesData { get; set; } = null;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            // Load the device data from the database
            using var context = await DbContextFactory.CreateDbContextAsync();
            var devices = await context.Minis.Include(m => m.Usuarios).ToListAsync();
            this.DevicesData = devices;
            StateHasChanged();
        }
    }

    private async Task ToggleDeviceStatus(MiniDTO device)
    {
        using var context = await DbContextFactory.CreateDbContextAsync();
        
        context.Attach(device);
        
        if (device.Estado == SmartHome.Shared.Constantes.EstadoEnum.Off)
        {
            device.Estado = SmartHome.Shared.Constantes.EstadoEnum.On;
        }
        else
        {
            device.Estado = SmartHome.Shared.Constantes.EstadoEnum.Off;
        }
        
        await context.SaveChangesAsync();
        StateHasChanged();
    }
}

