// <auto-generated/>
using Microsoft.AspNetCore.Components;
using Microsoft.EntityFrameworkCore;
using SmartHome.Shared.Entities;
using SmartHome.Shared.Persistence;

namespace SmartHome.Frontend.Components.Pages.Dispositivos;

public partial class MinisIndexComponent : ComponentBase
{
    [Inject]
    private IDbContextFactory<SmartHomeDbContext> DbContextFactory { get; set; } = default!;

    private List<MiniDTO>? DevicesData { get; set; } = null;

    protected override Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            // Load the device data from the database
            using var context = DbContextFactory.CreateDbContext();
            var device = context.Minis.Include(m => m.Usuarios);
            if (device != null)
            {
                this.DevicesData = device.ToList();
                StateHasChanged();
            }
        }
        return base.OnAfterRenderAsync(firstRender);
    }
}

