// <auto-generated/>
using Microsoft.AspNetCore.Components;

namespace SmartHome.Frontend.Components.Pages
{
    public partial class Home : ComponentBase
    {

        private void OnClick()
        {
            
        }
    }
}
