<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <Compile Remove="data\**" />
    <Content Remove="data\**" />
    <EmbeddedResource Remove="data\**" />
    <None Remove="data\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartHome.Shared\SmartHome.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
